version: '3.8'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=elasticsearch-cluster
            - discovery.type=single-node
            - ELASTIC_PASSWORD=elasticsearch
        ports:
            - '9200:9200'
            - '9300:9300'
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - elastic

volumes:
    elasticsearch-data:
        driver: local

networks:
    elastic:
        driver: bridge
